//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammSolvesForBusiness.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Агент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Агент()
        {
            this.Продажа = new HashSet<Продажа>();
        }
    
        public string Тип_агента { get; set; }
        public string Наименование_агента { get; set; }
        public string Электронная_почта_агента { get; set; }
        public string Телефон_агента { get; set; }
        public string Логотип_агента { get; set; }
        public string Юридический_адрес { get; set; }
        public short Приоритет { get; set; }
        public string Директор { get; set; }
        public long ИНН { get; set; }
        public int КПП { get; set; }
        public int Код_агента { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажа> Продажа { get; set; }
    }
}
