//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammSolvesForBusiness.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажа
    {
        public int ID { get; set; }
        public System.DateTime Дата_продажи { get; set; }
        public System.TimeSpan Время_продажи { get; set; }
        public int Код_агента { get; set; }
        public int Код_продукции { get; set; }
    
        public virtual Агент Агент { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
